### ISSUE TITLE
Fixing "from palme.model import PALME" in train.py

### ISSUE THREAD

**Issue by aakb101** [kyegomez/PALM-E#3]
I think this "from palme.model import PALME" has to be "    from palme.model import PalmE" ?

**Comment by kyegomez** [comment]
Hey did you pip install or where are you getting this eror?

**Comment by aakb101** [comment]
I'm getting the following error when I run python3 train.py:
```
line 44, in <module>
    from palme.model import PALME
ImportError: cannot import name 'PALME' from 'palme.model'
```

**Comment by kyegomez** [comment]
@aakb101 Hey please excuse me for this dumb small error, it is fixed now.
